---
name: Terraform

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  terraform:
    uses: dhoppeIT/github-reusable-workflows/.github/workflows/terraform_cloud.yaml@main
    with:
      multiple_workspaces: true
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
